id: ID7F34144
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:42:11.705858
last_modified: 2023-02-09 14:42:11.705975
source_metadata:
  title: 'BA: Gaṇḍavyūhasūtra'
  language: bo
bases:
  6FB4:
    base_file: 6FB4.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
